### ISSUE TITLE
Send user agent header with requests

### ISSUE THREAD

**Issue by balajikris** [Azure/azure-sdk-for-node#2076]
Implement https://github.com/Azure/azure-sdk-for-ruby/issues/517 for node sdk

**Tasks:**
- [x] changes to runtime are merged 
- [x] updated runtime packages published to npm. 
- [x] changes to Autorest are merged. 
- [x] Regenerate all autorest generated packages and publish them to npm.

**Comment by balajikris** [comment]
This is all checked in and released as of today.
